service: aws-node-rest-api

frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs14.x
    region: eu-north-1
    iamRoleStatements:
        - Effect: Allow
          Action:
          - dynamodb:*
          Resource:
          - ${file(./config.json):ARN}

functions:
    signup:
        handler: src/signUp.handler
        events:
            - http:
                  path: /signup
                  method: post

    allusers:
        handler: src/allUsers.handler
        events:
            - http:
                  path: /allusers
                  method: get
                
    signin:
        handler: src/signIn.handler
        events:
            - http:
                  path: /signin
                  method: post

resources:
    Resources:
        JwtUsersTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: JwtUsersTable
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH

            
